# Form implementation generated from reading ui file 'e:\python\WeekDayCountDown\Ui_nmcd.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(889, 452)
        Form.setStyleSheet("background-color: lightgray;")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(280, 300, 341, 121))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.pushButton.setObjectName("pushButton")
        self.lcdNumber = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber.setEnabled(True)
        self.lcdNumber.setGeometry(QtCore.QRect(450, 140, 71, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber.setFont(font)
        self.lcdNumber.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(1)
        self.lcdNumber.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber.setProperty("intValue", 8)
        self.lcdNumber.setObjectName("lcdNumber")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser.setGeometry(QtCore.QRect(40, 140, 411, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_2.setGeometry(QtCore.QRect(520, 140, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber_2.setEnabled(True)
        self.lcdNumber_2.setGeometry(QtCore.QRect(20, 20, 141, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber_2.setFont(font)
        self.lcdNumber_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber_2.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber_2.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber_2.setSmallDecimalPoint(False)
        self.lcdNumber_2.setDigitCount(4)
        self.lcdNumber_2.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_2.setProperty("intValue", 8888)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber_3.setEnabled(True)
        self.lcdNumber_3.setGeometry(QtCore.QRect(220, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber_3.setFont(font)
        self.lcdNumber_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber_3.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber_3.setSmallDecimalPoint(False)
        self.lcdNumber_3.setDigitCount(2)
        self.lcdNumber_3.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_3.setProperty("value", 88.0)
        self.lcdNumber_3.setProperty("intValue", 88)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.textBrowser_3 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_3.setGeometry(QtCore.QRect(160, 20, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_3.setFont(font)
        self.textBrowser_3.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_3.setObjectName("textBrowser_3")
        self.textBrowser_4 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_4.setGeometry(QtCore.QRect(290, 20, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_4.setFont(font)
        self.textBrowser_4.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_4.setObjectName("textBrowser_4")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber_4.setEnabled(True)
        self.lcdNumber_4.setGeometry(QtCore.QRect(350, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber_4.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber_4.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber_4.setSmallDecimalPoint(False)
        self.lcdNumber_4.setDigitCount(2)
        self.lcdNumber_4.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_4.setProperty("intValue", 88)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.textBrowser_5 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_5.setGeometry(QtCore.QRect(420, 20, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_5.setFont(font)
        self.textBrowser_5.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_5.setObjectName("textBrowser_5")
        self.line_2 = QtWidgets.QFrame(parent=Form)
        self.line_2.setGeometry(QtCore.QRect(340, 90, 51, 51))
        self.line_2.setStyleSheet("border-color: black;\n"
"background-color:none;")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBrowser_6 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_6.setGeometry(QtCore.QRect(620, 140, 91, 71))
        self.textBrowser_6.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_6.setObjectName("textBrowser_6")
        self.line_3 = QtWidgets.QFrame(parent=Form)
        self.line_3.setGeometry(QtCore.QRect(620, 350, 51, 21))
        self.line_3.setStyleSheet("border-color: black;\n"
"background-color:none;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(parent=Form)
        self.line_4.setGeometry(QtCore.QRect(640, 210, 61, 151))
        self.line_4.setStyleSheet("border-color: black;\n"
"background-color:none;")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_6 = QtWidgets.QFrame(parent=Form)
        self.line_6.setGeometry(QtCore.QRect(640, 90, 61, 51))
        self.line_6.setStyleSheet("border-color: black;\n"
"background-color:none;")
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber_5.setEnabled(True)
        self.lcdNumber_5.setGeometry(QtCore.QRect(610, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber_5.setFont(font)
        self.lcdNumber_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber_5.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber_5.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setDigitCount(2)
        self.lcdNumber_5.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_5.setProperty("intValue", 88)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.textBrowser_7 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_7.setGeometry(QtCore.QRect(680, 20, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_7.setFont(font)
        self.textBrowser_7.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_7.setObjectName("textBrowser_7")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber_6.setEnabled(True)
        self.lcdNumber_6.setGeometry(QtCore.QRect(740, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber_6.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.lcdNumber_6.setDigitCount(2)
        self.lcdNumber_6.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_6.setProperty("intValue", 88)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.textBrowser_8 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_8.setGeometry(QtCore.QRect(810, 20, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_8.setFont(font)
        self.textBrowser_8.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_8.setObjectName("textBrowser_8")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(parent=Form)
        self.lcdNumber_7.setEnabled(True)
        self.lcdNumber_7.setGeometry(QtCore.QRect(480, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.lcdNumber_7.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.lcdNumber_7.setStyleSheet("color: red;\n"
"background-color: rgb(199, 199, 199)")
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setDigitCount(2)
        self.lcdNumber_7.setMode(QtWidgets.QLCDNumber.Mode.Dec)
        self.lcdNumber_7.setProperty("intValue", 88)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.textBrowser_9 = QtWidgets.QTextBrowser(parent=Form)
        self.textBrowser_9.setGeometry(QtCore.QRect(550, 20, 61, 71))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.textBrowser_9.setFont(font)
        self.textBrowser_9.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.textBrowser_9.setObjectName("textBrowser_9")
        self.checkBox = QtWidgets.QCheckBox(parent=Form)
        self.checkBox.setGeometry(QtCore.QRect(730, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily("思源黑体 CN")
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("background-color: rgb(199, 199, 199)")
        self.checkBox.setObjectName("checkBox")
        self.line_5 = QtWidgets.QFrame(parent=Form)
        self.line_5.setGeometry(QtCore.QRect(670, 260, 61, 21))
        self.line_5.setStyleSheet("border-color: black;\n"
"background-color:none;")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "点击检查时间"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:36pt;\">距离设定时间还剩</span></p></body></html>"))
        self.textBrowser_2.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Microsoft YaHei UI\'; font-size:36pt;\">天</span></p></body></html>"))
        self.textBrowser_3.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">年</span></p></body></html>"))
        self.textBrowser_4.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">月</span></p></body></html>"))
        self.textBrowser_5.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">日</span></p></body></html>"))
        self.textBrowser_6.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\">API</span></p></body></html>"))
        self.textBrowser_7.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">分</span></p></body></html>"))
        self.textBrowser_8.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">秒</span></p></body></html>"))
        self.textBrowser_9.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'思源黑体 CN\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:28pt;\">时</span></p></body></html>"))
        self.checkBox.setText(_translate("Form", "重复执行"))
